<footer>
	<div class="container">
		<div class="pure-g-r">
			<div class="pure-u-2-5">
				<h2 class="main-title">The aberdeens</h2>
			</div>
			<div class="pure-u-2-5">
				<p>Gracias por haber leído hasta acá. Este es un texto de prueba.</p>
			</div>
			<div class="pure-u-1-5">
				<a href="#" id="up">
					<i class="fa fa-chevron-circle-up"></i>
				</a>
			</div>			
		</div>
	</div>
</footer>