<!DOCTYPE html>
<!--
 	_     _ _______                _____   
	|_____| |______ |      |      |     |  
	|     | |______ |_____ |_____ |_____|.
 
 	Que leas esto significa que te gusta el código como a mi (:
 	Puedes contactarme en durancristhian@gmail.com
-->
<html>
<head>
	<title>Express 4.x</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no">
    <meta name="description" content="Express 4.x.">
	<link rel="stylesheet" type="text/css" href="/css/production.css">

	<!--[if lt IE 9]>
        <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
        <script>window.html5 || document.write('<script src="/js/vendor/html5shiv.js"><\/script>')</script>
    <![endif]-->
<body>

	{% block content %}{% endblock %}

	<script type="text/javascript" src="/js/production.min.js"></script>
</body>
</html>